Removed local repo lines
alces-software/metalware-default pull request #3
Opened 2017-06-29 13:29 UTC by ColonelPanicks

Local repository setup is now going to be handled outside of metalware-defaults. New local repo setup will be described in the HPC Cluster Platform Knowledgebase. 

_Note: I have tested deploying a VM using this branch and didn't hit any issues regarding yum repos_

2017-06-29 13:44 UTC, BobWhitelock commented
Looks reasonable to me if this is a change we want to make (which I imagine @ste78 knows more about).

One question, do we want to remove the `files/core/configs/yum.*` files themselves now since they're unused?

2017-06-29 13:45 UTC, ColonelPanicks commented
Oops, yeah the local yum conf files should be removed as well, will sort that now.

2017-06-29 13:46 UTC, BobWhitelock commented
OK, LGTM then!

2017-06-29 13:46 UTC, bobwhitelock approved these changes

2017-06-29 17:47 UTC, sierra-tango-echo requested changes

2017-06-29 17:47 UTC, ste78 commented on files/core/base.sh
> +yum -y install yum-utils
You can take the yum-utils line out as well, install it as part of your client local repo setup script

2017-06-30 12:42 UTC, ColonelPanicks commented on files/core/base.sh
> +yum -y install yum-utils
Done in commit 4d6cdf3

2017-06-30 12:43 UTC, sierra-tango-echo approved these changes

2017-06-30 12:48 UTC, merged